application:
  appName: "mcenter"
  description: "微服务用户中心"
  domain: "example.com"

log:
  otlp: true

http:
  enabled: true
  host: "0.0.0.0"
  port: 8082
  otlp: true

grpc:
  enabled: true
  otlp: true
  host: "0.0.0.0"
  port: 18082
  token: "mcenter-token"


otlp:
  httpEndpoint: "10.54.44.78:4318"
  grpcEndpoint: "10.54.44.78:4317"
  enableTLS: false

datasource:
  otlp: true
  host: "127.0.0.1"
  port: 3306
  database: "CloudManager"
  username: "root"
  password: "redhat"
  debug: true


mcenterClient:
  host: "127.0.0.1"
  port: 18082
  token: "mcenter-token"


tokenProvider:
  # 润工作
#  appID: "cli_9e063da4943a1008"
#  appSecret: "DTRJz5iWdqbjZEbCE6FB8waYQzYEMexH"
#  baseUrl: "https://open.rwork.crc.com.cn"
  # 自建
  appID: "cli_a67e7234b5bd100d"
  appSecret: "qvYXwDwg6A2sygtV6RJI0IOUNYtTX8vo"
  baseUrl: "https://open.feishu.cn"
